url: https://astrucmodules.fr/
baseurl:

gems:
  - jekyll-sitemap

# Site settings
title: AstrucModules - Conception & fabrication de modules en bois pour l'escalade
email: whysyy@gmail.com
description: "AstrucModules vente et fabrication sur mesure de modules/volumes en bois pour les murs d'escalades. Fabrication artisanal et française."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Clement Astruc
  pic: clement_astruc
  position: Fondateur
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Astrucmodules/

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty

# Description module
couleur:
  - nom: Bleu
    code: 0165a3
  - nom: Rouge
    code: e00000
  - nom: Jaune
    code: f2c001
  - nom: Gris graphite
    code: 363b42
  - nom: Gris poussi&egrave;re
    code: 7d7f7d
  - nom: Noir
    code: 09090c
  - nom: Orange
    code: d47a04    
  - nom: Rose
    code: be4e80    
  - nom: Vert
    code: 89ae2d    
avertissement : Les vis de fixation sont fournies avec le module.

languages: ["fr", "en"]
exclude_from_localizations: ["javascript", "images", "css"]
